# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 23:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fluentcms_forms_builder', '0002_auto_20160708_1024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='formitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
