# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluentcms_forms_builder', '0003_auto_20181129_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='formitem',
            name='show_form_intro',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show form intro'),
        ),
        migrations.AddField(
            model_name='formitem',
            name='show_form_title',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show form title'),
        ),
    ]
